version: "3"
services:
  seleniumfw:
    image: amitdocker369/selfw
    environment:
    - HUB_HOST=hub
    - BROWSER=${BROWSER}
    - THREAD_COUNT=2
    volumes:
    - ./output/test-output:/home/selenium-docker/test-output
    - ./output/reports:/home/selenium-docker/reports